name: CI Pipeline

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  
jobs:

  build:  
    name: Build and tests UI and API
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --no-restore

    - name: Execute API tests
      run: dotnet test --filter "Category=API"
      continue-on-error: true

    - name: Upload API logs
      uses: actions/upload-artifact@v4
      with:
        name: api-test-logs
        path: |
          Logs/
